name: QC

on:
  push:
    branches:
      - main

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@e70e07ef05f0a3bf1483fde3c50eeab9c1805041 # v1.0.1

  static_analysis:
    name: Run static analysis
    needs: security_hardening
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.get-flutter-version.outputs.version }}
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Get Flutter version
      id: get-flutter-version
      uses: zgosalvez/github-actions-get-flutter-version-env@8c616b4685d25cceda9bafa61f6c72670f6aa01e # v1.1.1
    - name: Set up Flutter
      uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136 # v1.4.0
      with:
        flutter-version: ${{ steps.get-flutter-version.outputs.version }}
    - name: Cache Flutter packages
      id: cache
      uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a # v2.1.3
      with:
        path: | # https://github.com/subosito/flutter-action/blob/26bf50084a0c218b5b715a3641c36eac84fd2136/src/installer.ts#L37
          ${{ format('{0}/.pub-cache', env.FLUTTER_HOME) }} 
          ${{ format('{0}/bin/.pub-cache', env.FLUTTER_HOME) }}
        key: pub-${{ env.cache-name }}-${{ steps.get-flutter-version.outputs.version }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          pub-${{ env.cache-name }}-${{ steps.get-flutter-version.outputs.version }}-
          pub-${{ env.cache-name }}-
          pub-
      env:
        cache-name: cache-flutter-packages
    - name: Get Flutter packages
      run: flutter pub get ${{ steps.cache.outputs.cache-hit == 'true' && '--offline' || '' }}
    - name: Analyze Flutter
      uses: zgosalvez/github-actions-analyze-flutter@337a56d93e405a585348c0695b420b3d1f5887e6 # v1.0.3

  testing:
    name: Run ${{ matrix.category }} testing
    needs: static_analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [unit, widget]
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Set up Flutter
      uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136 # v1.4.0
      with:
        flutter-version: ${{ needs.static_analysis.outputs.flutter_version }}
    - name: Cache Flutter packages
      id: cache
      uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a # v2.1.3
      with:
        path: | # https://github.com/subosito/flutter-action/blob/26bf50084a0c218b5b715a3641c36eac84fd2136/src/installer.ts#L37
          ${{ format('{0}/.pub-cache', env.FLUTTER_HOME) }} 
          ${{ format('{0}/bin/.pub-cache', env.FLUTTER_HOME) }}
        key: pub-${{ env.cache-name }}-${{ needs.static_analysis.outputs.flutter_version }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: |
          pub-${{ env.cache-name }}-${{ needs.static_analysis.outputs.flutter_version }}-
          pub-${{ env.cache-name }}-
          pub-
      env:
        cache-name: cache-flutter-packages
    - name: Get Flutter packages
      run: flutter pub get ${{ steps.cache.outputs.cache-hit == 'true' && '--offline' || '' }}
    - name: Run Flutter ${{ matrix.category }} tests
      run: flutter test --coverage --coverage-path=./coverage/lcov.${{ matrix.category }}.info test/${{ matrix.category }}s
    - name: Upload code coverage to GitHub
      uses: actions/upload-artifact@726a6dcd0199f578459862705eed35cda05af50b # v2.2.1
      with:
        name: code-coverage
        path: coverage/lcov.${{ matrix.category }}.info

  coverage_report:
    name: Generate coverage report
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Install lcov
      run: sudo apt-get install lcov
    - name: Download code coverage from GitHub
      uses: actions/download-artifact@f144d3c3916a86f4d6b11ff379d17a49d8f85dbc # v2.0.7
      with:
        name: code-coverage
        path: coverage
    - name: Create HTML output for coverage data
      run: genhtml coverage/lcov.unit.info coverage/lcov.widget.info --output-directory coverage/html
    - name: Upload code coverage report to GitHub
      uses: actions/upload-artifact@726a6dcd0199f578459862705eed35cda05af50b # v2.2.1
      with:
        name: code-coverage-report
        path: coverage/html
